USE ROLE SYSADMIN;

SHOW WAREHOUSES;

CREATE WAREHOUSE marketing_wh
WITH
WAREHOUSE_SIZE = 'X-Small'
AUTO_SUSPEND = 60
AUTO_RESUME =TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Exercise 1 comment :)';

SHOW WAREHOUSES;