SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;

SHOW TABLES;

SHOW VIEWS;

USE SCHEMA DATAFEEDS;

SELECT * FROM GOOGLE_KEYWORDS LIMIT 10;

SELECT COUNT(*) FROM GOOGLE_KEYWORDS;

DESCRIBE TABLE GOOGLE_KEYWORDS;