SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;

SHOW TABLES;

SHOW VIEWS;

USE SCHEMA DATAFEEDS;

SELECT * FROM GOOGLE_KEYWORDS LIMIT 10;

SELECT COUNT(*) FROM GOOGLE_KEYWORDS;

DESCRIBE TABLE GOOGLE_KEYWORDS;

-- C)
SELECT COUNT(*) FROM GOOGLE_KEYWORDS;

SELECT DATE
FROM GOOGLE_KEYWORDS
ORDER BY DATE ASC
LIMIT 10;

-- D) (2 queries som man union tillsammans för att få båda raderna direkt)
(
    SELECT *
    FROM GOOGLE_KEYWORDS
    ORDER BY DATE ASC
    LIMIT 1
)
UNION ALL
(
    SELECT *
    FROM GOOGLE_KEYWORDS
    ORDER BY DATE DESC
    LIMIT 1
);

-- E)
SELECT KEYWORD, COUNT(*) AS Number_Of_Searches
FROM GOOGLE_KEYWORDS
GROUP BY KEYWORD
ORDER BY Number_Of_Searches DESC
LIMIT 10;

-- F)
SELECT COUNT(DISTINCT KEYWORD) AS UNIQUE_KEYWORDS
FROM GOOGLE_KEYWORDS;

-- G)
SELECT DISTINCT PLATFORM, COUNT(*) AS USERS_PER_PLATFORM
FROM GOOGLE_KEYWORDS
GROUP BY PLATFORM;

-- H)
SELECT KEYWORD, COUNT(*) AS NUMBER_OF_SEARCHES
FROM GOOGLE_KEYWORDS
WHERE COUNTRY = 752
GROUP BY KEYWORD
ORDER BY NUMBER_OF_SEARCHES DESC
LIMIT 20;

-- I)
SELECT COUNTRY, KEYWORD, COUNT(*) AS NUMBER_OF_SERCHES
FROM GOOGLE_KEYWORDS 
WHERE KEYWORD = 'spotify'
GROUP BY COUNTRY, KEYWORD
ORDER BY NUMBER_OF_SERCHES DESC
LIMIT 10;

-- J)
-- NEJ TACK.